apiVersion: v1
kind: Service
metadata:
  name: kus-kus-images
spec:
  selector:
    app: kus-kus-images
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kus-kus-images
spec:
  selector:
    matchLabels:
      app: kus-kus-images
  replicas: 1
  template:
    metadata:
      labels:
        app: kus-kus-images
    spec:
      containers:
        - name: kus-kus-images
          image: blink182u2/kus-kus-images:0.0.1-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 300m
              memory: 750Mi
      serviceAccountName: kuskusstackstackkuskusclusterkuskusimageseddad571
